### ISSUE TITLE
CLI tool?

### ISSUE THREAD

**Issue by kaelig** [vadimdemedes/leeroy-jenkins#1]
Thank you for publishing the greatest npm package of all time.

I dream of a world where this is possible:

```
alias leeroy=git push --force && leeroy-jenkins
```

Can you make it happen, oh lord of JS?

**Comment by vadimdemedes** [comment]
I, the lord of JS, heard your voice, my son. Dreams do come true and to prove that, here's a CLI you wished for - https://github.com/vadimdemedes/leeroy-jenkins-cli. May this invaluable tool serve you well. Try it and observe how it 10x'es the happiness and productivity of your team.
